In [13]:
import numpy as np 
from scipy.stats import t
import statistics

####
def calc_CI(sf_cnt, confidence=0.95):
    l_exon_cnt=[]
    l_high_pLI_cnt=[]
    with open(sf_cnt) as fin:
        for line in fin:
            fields=line.rstrip().split()
            i_exon=float(fields[0])
            i_high_pLI=float(fields[1])
            l_exon_cnt.append(i_exon)
            l_high_pLI_cnt.append(i_high_pLI)

    ci_exon=np.percentile(l_exon_cnt,[100*(1-confidence)/2,100*(1-(1-confidence)/2)]) 
    f_mean_exon=statistics.mean(l_exon_cnt)
    ci_high_pLI=np.percentile(l_high_pLI_cnt,[100*(1-confidence)/2,100*(1-(1-confidence)/2)]) 
    f_mean_pLI=statistics.mean(l_high_pLI_cnt)
    return ci_exon, f_mean_exon, ci_high_pLI, f_mean_pLI

sf_prefix="/Users/simon/research/projects/xTEA_denovo_rslts/rslts_kids_first/summary_results/enrichment_analysis/rslts/simulation_by_cleavage_sits/"

sf_cnt_Alu=sf_prefix+"summarized_cnt_all_rounds_Alu.txt"
ci_exon_alu, f_mean_exon_alu, ci_high_pLI_alu, f_mean_high_pLI_alu = calc_CI(sf_cnt_Alu)

sf_cnt_SVA=sf_prefix+"summarized_cnt_all_rounds_SVA.txt"
ci_exon_sva, f_mean_exon_sva, ci_high_pLI_sva, f_mean_high_pLI_sva = calc_CI(sf_cnt_SVA)

sf_cnt_L1=sf_prefix+"summarized_cnt_all_rounds_L1.txt"
ci_exon_l1, f_mean_exon_l1, ci_high_pLI_l1, f_mean_high_pLI_l1 = calc_CI(sf_cnt_L1)

sf_out_exon=sf_prefix+"exon_95_CI_mean.csv" #
sf_out_pLI=sf_prefix+"high_pLI_CI_mean.csv"
with open(sf_out_exon,"w") as fout_exon, open(sf_out_pLI,"w") as fout_pLI:
    fout_exon.write("Repeat,CI_lower,CI_upper,Mean\n")
    fout_exon.write("Alu,%f,%f,%f\n"%(ci_exon_alu[0], ci_exon_alu[1], f_mean_exon_alu))
    fout_exon.write("L1,%f,%f,%f\n"%(ci_exon_l1[0], ci_exon_l1[1], f_mean_exon_l1))
    fout_exon.write("SVA,%f,%f,%f\n"%(ci_exon_sva[0], ci_exon_sva[1], f_mean_exon_sva))
    
    fout_pLI.write("Repeat,CI_lower,CI_upper,Mean\n")
    fout_pLI.write("Alu,%f,%f,%f\n"%(ci_high_pLI_alu[0], ci_high_pLI_alu[1], f_mean_high_pLI_alu))
    fout_pLI.write("L1,%f,%f,%f\n"%(ci_high_pLI_l1[0], ci_high_pLI_l1[1], f_mean_high_pLI_l1))
    fout_pLI.write("SVA,%f,%f,%f\n"%(ci_high_pLI_sva[0], ci_high_pLI_sva[1], f_mean_high_pLI_sva))

#
#
#####
#####

In [2]:
import numpy as np 
from scipy.stats import t
import statistics

x = np.random.normal(size=100)
values = [np.random.choice(x,size=len(x),replace=True).mean() for i in range(1000)] 
np.percentile(values,[100*(1-confidence)/2,100*(1-(1-confidence)/2)]) 


NameError: name 'confidence' is not defined

In [31]:
from scipy import stats
import numpy
def calc_pvalue(sf_cnt, i_obs_exon, i_obs_high_pLI):
    l_exon_cnt=[]
    l_high_pLI_cnt=[]
    with open(sf_cnt) as fin:
        for line in fin:
            fields=line.rstrip().split()
            i_exon=int(fields[0])
            i_high_pLI=int(fields[1])
            l_exon_cnt.append(i_exon)
            l_high_pLI_cnt.append(i_high_pLI)
    #convert list to np array
    arr_exon_cnt = numpy.array(l_exon_cnt)
    print(arr_exon_cnt)
    aa=stats.ttest_1samp(arr_exon_cnt,i_obs_exon)
    print(aa)
    
    arr_high_pLI_cnt = numpy.array(l_high_pLI_cnt)
    bb=stats.ttest_1samp(l_high_pLI_cnt,i_obs_high_pLI)
    print(bb)
    
    p_value_exon=0
    p_value_pLI=0
    return p_value_exon, p_value_pLI
    
sf_cnt_SVA=sf_prefix+"summarized_cnt_all_rounds_SVA.txt"
i_sva_obs_exon=3
i_sva_obs_high_pLI=9
pvalue_exon, pvalue_high_pLI = calc_pvalue(sf_cnt_SVA, i_sva_obs_exon, i_sva_obs_high_pLI)
print(pvalue_exon) #

sf_cnt_Alu=sf_prefix+"summarized_cnt_all_rounds_Alu.txt"
i_alu_obs_exon=6
i_alu_obs_high_pLI=14
pvalue_exon, pvalue_high_pLI = calc_pvalue(sf_cnt_Alu, i_alu_obs_exon, i_alu_obs_high_pLI)

sf_cnt_L1=sf_prefix+"summarized_cnt_all_rounds_L1.txt"
i_l1_obs_exon=0
i_l1_obs_high_pLI=2
pvalue_exon, pvalue_high_pLI = calc_pvalue(sf_cnt_L1, i_l1_obs_exon, i_l1_obs_high_pLI)

##

[0 1 2 ... 1 2 1]
Ttest_1sampResult(statistic=-217.30259774741486, pvalue=0.0)
Ttest_1sampResult(statistic=-212.47414199553526, pvalue=0.0)
0
[0 2 6 ... 4 7 1]
Ttest_1sampResult(statistic=-215.96235933765706, pvalue=0.0)
Ttest_1sampResult(statistic=-36.92037845968045, pvalue=7.532022209821414e-280)
[0 3 0 ... 1 0 0]
Ttest_1sampResult(statistic=91.16634077110459, pvalue=0.0)
Ttest_1sampResult(statistic=110.91241806664672, pvalue=0.0)


In [29]:
from scipy import stats
rvs = stats.norm.rvs(loc = 5, scale = 10, size = (50,1))
l_test=[]
for a in rvs:
    for b in a:
        l_test.append(b)
print(l_test)
arr_test = numpy.array(l_test)
print(arr_test)
print(stats.ttest_1samp(arr_test,5.0))
print(stats.ttest_1samp(rvs,5.0))


[-2.6726542607103223, 11.973763747014983, -8.691092036857924, 5.82409591191669, 5.995111123673747, 4.448685248002518, 1.440632977551262, -6.682266832516666, -3.4723636719684166, 16.61937687739222, 8.342674036493174, 7.90857051857634, -6.082741170424541, -9.721551357128531, 4.743726189867675, -3.8829719092963426, 3.0499965527060624, -24.149695307031593, 8.051294133663273, 10.834564996922293, 15.686826077958498, -1.686335947427553, -4.561388621649062, -18.73887261926724, 12.252888241517086, 11.214574057462217, 14.034931640149997, 6.564770253633174, 1.863356105000495, -10.455606680450833, 11.775402432177017, -2.4520565805791783, 8.71361449535179, 15.49714805364981, 4.604590393094418, 14.593186241626682, 1.748881337183783, 4.830732715398015, 11.718523569681487, 2.0279460254333506, 29.363047443858136, 3.692771129983318, 16.93337903452207, 9.19422755408352, -1.8943148680299116, -18.63975541991757, -10.960576411271362, 4.491584660835805, 19.861743486919885, -6.789352783776096]
[ -2.67265426  

In [41]:
from scipy import stats
rvs = stats.norm.rvs(loc = 5, scale = 10, size = (50,2))
print(stats.ttest_1samp(rvs,5.0))

Ttest_1sampResult(statistic=array([ 0.61064685, -0.25867191]), pvalue=array([0.54425559, 0.79697192]))
